### PR TITLE
Features - Sign up an Sign in UIs

### PR DESCRIPTION
**Pull request by Arnoldmn**
Kindly merge and advice accordingly

### CODE REVIEW

**Review by GradiMut — CHANGES_REQUESTED** [review]
Nice Work guys @Mumbere7 & @yemmighto, you need to make some change before it could be merge : 
1. If you need to add color under resource, please add them but do not change what is already their(Primary, PrimaryDark & Accent). Those colors are used elsewhere & those are our them color.
2. I'm seeing 2 LoginActivity class, please delete 1 that is not useful.
3. In activity_login.xml & activity_signup.xml file(s). Replace android:text by android:hint and to change the color of the hint text use android:textColorHint. This is apply everywhere you used EditText.

Please do read above, and make the necessary change then send your Pull Request.

**Comment by Arnoldmn** [comment]
Okay

**Comment by Arnoldmn** [comment]
Check and see changes have been met.

**Comment by Arnoldmn** [comment]
There you go

**Review by GradiMut — APPROVED** [review]
Cool, though when i click on the register from the login page it crashes, try to look at it. @Mumber7

**Pull request merged**
